### ISSUE TITLE
Enhancement request - Add category filter to Bulletins

### ISSUE THREAD

**Issue by Rufus-1** [minagerges/AutoPatcher#11]
Hi,

Is it possible to add the patch category (Security Update, Service Pack...) to the filters in the bulletin section, this is for customers that only want to distribute security updates

Thanks,
R

**Comment by minagerges** [comment]
In consideration.

**Comment by Rufus-1** [comment]
Hi Mina,

Thanks for the update! Is there a possibility for assisting in the development?

Kind Regards,

Rufus Swart
  Professional Services Consultant

   Mobile:  +27 82 532 3250<tel:+27%2082%20532%203250>
   Email:  rufus@proserve.net.za<mailto:rufus@proserve.net.za>

[ProServe Consulting (PTY) Ltd]



Email Disclaimer:
The information contained in this communication is confidential and may be legally privileged. It is intended solely for the user of the individual or entity to whom it is addressed and others​ authorised to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking action in reliance of the contents of this information is strictly prohibited and may be unlawful.​ The Employer is neither liable for the proper, complete transmission of the information contained in this communication nor any delay in its receipt.

On 27 Sep 2017, at 21:17, Mina Gerges <notifications@github.com<mailto:notifications@github.com>> wrote:


In consideration.

**Comment by minagerges** [comment]
Thank you for your kind offer, but that is not possible.

**Comment by minagerges** [comment]
This feature is not feasible as the category information is not available in the DB.
Only guide for security updates is the description, which usually starts with the word "Security"

Accordingly I recommend create the policies "disabled", and enable the required ones manually.

**Comment by ChronoGuru** [comment]
> 
> 
> This feature is not feasible as the category information is not available in the DB.
> Only guide for security updates is the description, which usually starts with the word "Security"
> 
> Accordingly I recommend create the policies "disabled", and enable the required ones manually.

Following up on this issue slightly with a different approach:

Is it possible to implement a keyword filter for the KB name? This way we could create custom autopatcher XMLs based on what we want to deploy, using Microsoft's patch naming scheme.

For example, Microsoft labels their security updates starting with MSYEAR-MONTH-PRODUCTNAME-BULLETINNUMBER (e.g. MS20-04-OFF-KBxxxx). If we could create autopatcher XML's with a keyword filter for all bulletins that begin with "MS20", we'd successfully be able to deploy only security updates.

Keyword exclusions could also play into this. Include everything in the patch repository starting with "MS", but exclude everything in the patch repository that starts with "MSNS". That would provide this functionality.

Inclusions and exclusions based on the KB name would solve this I think, at least for Microsoft patching.

**Comment by ColbyMorgan** [comment]
This could be implemented with a regular expression filter on the bulletin names.  We would like to auto-deploy all Microsoft security updates, with the exception of certain products (Exchange & SQL).

In the following example, we would want policies auto-created for all bulletins except the SQL and EX updates:

MS20-02-SQL-453095
MS20-04-W10-4550969
MS20-03-EX-4540123
MS20-03-MR81-4541509
MS19-12-MRNET-4532997

A regular expression similar to this should match everything we desire to publish:
^MS\d{2}-\d{2}(?!-EX-|-SQL-)\S.*-\d.*

Appreciate all your work on AutoPatcher!
