### ISSUE TITLE
Error message "AutoPatcher | Unhandled exception"

### ISSUE THREAD

**Issue by XylAndreasM** [minagerges/AutoPatcher#12]
When running "AutoUpdater.exe" on my lab SMP, I get the error "Cannot bind to the new display member. Parameter name: newDisplayMember".

Version; 8.0.6365.23955

**Comment by minagerges** [comment]
Please provide full exception stack, and verbose SMP logs if possible.

**Comment by XylAndreasM** [comment]
My bad, Mina. I ran this on the lab and believed I had dbo access to the db with my account. Ran it with the proper appid, and it started fine. DBAs must have demoted my access. Sorry!
