### ISSUE TITLE
When I run AutoPatcher, The AutoPatcher will generate an error.

### ISSUE THREAD

**Issue by youchun83** [minagerges/AutoPatcher#16]
I have downloaded and run a new version of autoPatcher. If so, When I run AutoPatcher, The AutoPatcher will generate an error.
My SMP server is Windows 2012 R2. Existing version AutoPatcher 8.0.6365.23955 will run fine.

 
![123](https://user-images.githubusercontent.com/37096842/37465441-7645b1c8-289e-11e8-8cbf-15f9fb6b32d4.jpg)

--Detail—
Problem signature:
  Problem Event Name:                        CLR20r3
  Problem Signature 01:                      AutoPatcher.exe
  Problem Signature 02:                      8.0.6640.21880
  Problem Signature 03:                      5a9fba51
  Problem Signature 04:                      AutoPatcher
  Problem Signature 05:                      8.0.6640.21880
  Problem Signature 06:                      5a9fba51
  Problem Signature 07:                      1bf
  Problem Signature 08:                      4e
  Problem Signature 09:                      System.IO.FileNotFoundException
  OS Version:                                          6.3.9600.2.0.0.272.7
  Locale ID:                                             1033
  Additional Information 1:                 f536
  Additional Information 2:                 f536a6bcb56ab99a9a84961f6978269a
  Additional Information 3:                 5cbe
  Additional Information 4:                 5cbe8668737039d93588c3624b78549e

**Comment by minagerges** [comment]
I think you are running an older version of ITMS. I re-added backward compatibility to ITMS 8.0.
Please test with [Latest Release](https://github.com/minagerges/AutoPatcher/releases/latest) or upgrade to ITMS 8.1RU5

**Comment by minagerges** [comment]
Resolved by re-enabling backward compatibility to 8.0
