### ISSUE TITLE
AUTOPATCHER OPERATION FAILED!!! (System.NotSupportedException): Collection is read-only

### ISSUE THREAD

**Issue by ColbyMorgan** [minagerges/AutoPatcher#18]
Greetings,

We are currently evaluating SMC and our SE pointed me to AutoPatcher.  Overall it seems like a great addition, but I am having an issue with one feature.  I receive the following error when a target filter is selected:

Starting Distribution process for 93 Bulletins.
Found filter (Microsoft Autopatch Filter) - {aec72028-cc06-4c87-8c1f-3263c258cff9}, with no default target. Creating Target ...
Setting policy target to e6da8791-3564-46a4-910a-93f7deaafa3c
AUTOPATCHER OPERATION FAILED!!! (System.NotSupportedException): Collection is read-only.

Subsequent re-runs omit the "no default target. Creating Target" message.  I am running with an account that has system, SMC & SQL administrative access and have checked security on my filter and target.

I am running AutoPatcher 8.5.6884.33309 against SMC Version 8.5.3643.

Regards,
Colby

**Comment by minagerges** [comment]
Hello Colby,

Can you please enable verbose logging, reproduce the issue and provide (as attachment) a.log file (SMP log)

Also please provide additional information such as how this filter was created!

**Comment by ColbyMorgan** [comment]
Here are the logs and a screen shot of AutoPatcher.

Here is how I created the filter:
Clicked Manage \ Computers
Right Click -> New \ Filter
Name = Test Filter 20190314
Add Filter Criteria \ Name = morgan
Click Save Icon

![AutoPatcherConfig](https://user-images.githubusercontent.com/48528298/54385795-7cbe5380-4665-11e9-9e4c-b56d3b633d42.jpg)
[AutoPatcher.log](https://github.com/minagerges/AutoPatcher/files/2968170/AutoPatcher.log)
[AutoPatcher_SMP.log](https://github.com/minagerges/AutoPatcher/files/2968172/AutoPatcher_SMP.log)

**Comment by minagerges** [comment]
Thank you for the provided details.

Issue is fixed in [AutoPatcher 8.5.7013.28683](https://github.com/minagerges/AutoPatcher/releases/tag/8.5.7013.28683)

**Comment by ColbyMorgan** [comment]
Works perfect!  Thanks for the prompt response.
