### ISSUE TITLE
Custom Severity options?

### ISSUE THREAD

**Issue by ChronoGuru** [minagerges/AutoPatcher#19]
Hello!

We are in the process of rolling out the Symantec agent onto all of our environment and item we are trying to address it the ability to apply a custom severity level to Microsoft patches to escalate them if needed. 

I was wondering if there is a way to select a custom severity level that I've created through the management console, instead of using the default vendor provided severity levels?

Regards,
Scott

**Comment by minagerges** [comment]
Hello,

At the moment using custom severity is not feasible via AutoPatcher, however, I'm marking this as a feature, it might get included in a future release.

**Comment by minagerges** [comment]
Implemented in [8.5.7356.28305](https://github.com/minagerges/AutoPatcher/releases/tag/8.5.7356.28305)
