### ISSUE TITLE
AutoPatcher overwrites custom policies

### ISSUE THREAD

**Issue by ChronoGuru** [minagerges/AutoPatcher#20]
I've noticed that AutoPatcher removes custom policies we have created if they contain policies it wants to deploy. Can this behavior be modified to not touch any existing policies it did not create? I have tried placing the custom policies in different folders to no avail.

**Comment by minagerges** [comment]
Have you noticed the "policy overwrite" in the UI ?

For future assistance a full set of information must be provided, above description doesn't qualify.
