### ISSUE TITLE
Enhancement Request - Add Keyword/RegEx Filter to Bulletins

### ISSUE THREAD

**Issue by ColbyMorgan** [minagerges/AutoPatcher#21]
This was previously posted to an issue that was already closed.  Not sure if updates to closed issues are seen, so reposting (apologies if this is has been reviewed).
 
Would it be possible to implement a keyword filter on the bulletin name?  With this functionality, we could better target auto deployments based on vendor bulletin naming standards.  For example, Microsoft labels their security updates starting with MSYEAR-MONTH-PRODUCTNAME-BULLETINNUMBER (e.g. MS20-04-OFF-KBxxxx).   We would like to auto-deploy all Microsoft security updates, with the exception of certain products (Exchange & SQL).

This could be implemented with a regular expression filter on the bulletin name.  In the following example, we would want policies auto-created for all bulletins except the SQL and EX updates:

Auto publish:
MS20-04-W10-4550969
MS20-03-MR81-4541509
MS19-12-MRNET-4532997
Do not auto publish:
MS20-02-SQL-453095 
MS20-03-EX-4540123

In our example, a regular expression similar to this should match everything we desire to publish:
^MS\d{2}-\d{2}(?!-EX-|-SQL-)\S.-\d.

Appreciate all your work on AutoPatcher!

**Comment by minagerges** [comment]
Latest release  of AutoPatcher supports custom severity. 
You can implement whatever customised patter in a custom report, select the output and assign a custom severity to be used in AutoPatcher.
